### PR TITLE
Add credit card support

### PR DESCRIPTION
**Pull request by joaoalvarenga**

### CODE REVIEW

**Comment by lucasrcezimbra** [comment]
@joaoalvarenga I changed the base to `develop`. Can you merge `develop` into your branch?

**Comment by lucasrcezimbra** [comment]
@joaoalvarenga could you resolve conflicts and add tests for this `get_credit_card_invoice`?

**Comment by joaoalvarenga** [comment]
@lucasrcezimbra Done!

**Comment by joaoalvarenga** [comment]
@lucasrcezimbra Done! Can you take a look?

**Review by lucasrcezimbra — COMMENTED** [review]
Can you solve the conflicts?

**Review by lucasrcezimbra — APPROVED** [review]
Can you solve the conflicts?

**Pull request merged**
